version: "3.8"

services:
    nginx:
        build: requirements/nginx/
        image: nginx
        container_name: nginx
        ports:
          - "8000:443"
        volumes:
          - ${HOME_FOLDER}/data/wordpress:/var/www/html
    wordpress:
        build: requirements/wordpress/
        image: wordpress
        container_name: wordpress
        depends_on: 
          - mariadb
        volumes:
          - ${HOME_FOLDER}/data/wordpress:/var/www/html
        env_file: .env
    mariadb:
        build: requirements/mariadb
        image: mariadb
        container_name: mariadb
        volumes:
          - ${HOME_FOLDER}/data/mariadb:/var/lib/mysql
        environment:
          MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
          WP_DATABASE_NAME: ${WP_DATABASE_NAME}
          WP_DATABASE_USR:  ${WP_DATABASE_USR}
          WP_DATABASE_PWD:  ${WP_DATABASE_PWD}