FROM alpine:3.15

RUN apk update && apk upgrade && apk add --no-cache \
        mariadb \ 
		mariadb-client
RUN mkdir -p /run/mysqld
RUN chown -R mysql:mysql /run/mysqld
RUN chmod 777 /run/mysqld
RUN mysql_install_db --basedir=/usr --datadir=/var/lib/mysql \
--user=mysql --skip-test-db > /dev/null

COPY conf/configure.sh /tmp/configure.sh

ENTRYPOINT [ "sh", "/tmp/configure.sh" ]
