FROM alpine:3.15

RUN apk update && apk upgrade && apk add --no-cache \
        mariadb \ 
		mariadb-client
RUN mkdir -p /run/mysqld
RUN chown -R mysql:mysql /run/mysqld
RUN chmod 777 /run/mysqld

COPY conf/configure.sh /tmp/configure.sh
COPY conf/mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf

ENTRYPOINT [ "sh", "/tmp/configure.sh" ]
