FROM alpine:3.15

RUN		apk update && \
		apk add --no-cache nginx openssl

COPY ./conf/default.conf /etc/nginx/http.d/inception.conf
RUN mkdir /etc/nginx/ssl
RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
		-out /etc/nginx/ssl/nginx.pem \
		-keyout /etc/nginx/ssl/nginx.key \
		-subj "/C=NL/ST=Noord-Holland/L=Amsterdam/O=Codam/CN=ajanse.42.fr"

CMD [ "/usr/sbin/nginx", "-g", "daemon off;" ]